apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cilium-monitoring-rules
  # 需要设置在 prometheus 的 namespace 下
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/component: monitoring
    prometheus: kube-prometheus
    role: alert-rules
    # required by dce insight
    operator.insight.io/managed-by: insight
spec:
  groups:
  - name: cilium.agent.rules
    interval: 30s
    rules:
    # Agent 状态告警
    - alert: CiliumAgentDown
      expr: up{job="cilium-agent"} == 0
      for: 1m
      labels:
        severity: critical
        component: cilium-agent
      annotations:
        summary: "Cilium Agent 实例下线"
        description: "节点 {{ $labels.node }} 上的 Cilium Agent 已经下线超过 1 分钟"

    - alert: CiliumAgentErrorRateHigh
      expr: sum(rate(cilium_errors_warnings_total{level="error"}[5m])) by (node) > 0.1
      for: 2m
      labels:
        severity: warning
        component: cilium-agent
      annotations:
        summary: "Cilium Agent 错误率过高"
        description: "节点 {{ $labels.node }} 上的 Cilium Agent 错误率为 {{ $value }} 错误/秒，持续 2 分钟"

    - alert: CiliumUnreachableNodesHigh
      expr: cilium_unreachable_nodes > 1
      for: 5m
      labels:
        severity: warning
        component: cilium-agent
      annotations:
        summary: "Cilium 不可达节点数量过多"
        description: "节点 {{ $labels.node }} 上的 Cilium Agent 检测到 {{ $value }} 个不可达节点，持续 5 分钟"

    - alert: CiliumUnreachableEndpointsHigh
      expr: cilium_unreachable_health_endpoints > 5
      for: 5m
      labels:
        severity: warning
        component: cilium-agent
      annotations:
        summary: "Cilium 不可达端点数量过多"
        description: "节点 {{ $labels.node }} 上的 Cilium Agent 检测到 {{ $value }} 个不可达健康端点，持续 5 分钟"

    - alert: CiliumHealthzAPISlowResponse
      expr: sum(rate(cilium_agent_api_process_time_seconds_sum{path="/v1/healthz"}[5m])) by (node) / sum(rate(cilium_agent_api_process_time_seconds_count{path="/v1/healthz"}[5m])) by (node) > 1
      for: 3m
      labels:
        severity: warning
        component: cilium-agent
      annotations:
        summary: "Cilium Agent healthz API 响应缓慢"
        description: "节点 {{ $labels.node }} 上的 Cilium Agent healthz API 平均响应时间为 {{ $value }}秒，超过 1 秒阈值"

    - alert: CiliumBPFProgramLoadFailure
      expr: count(cilium_bpf_progs == 0) > 0
      for: 1m
      labels:
        severity: critical
        component: cilium-agent
      annotations:
        summary: "Cilium BPF 程序加载失败"
        description: "有 {{ $value }} 个 Cilium Agent 节点的 BPF 程序加载异常"

  - name: cilium.operator.rules
    interval: 30s
    rules:
    # Operator 状态告警
    - alert: CiliumOperatorDown
      expr: up{job="cilium-operator"} == 0
      for: 1m
      labels:
        severity: critical
        component: cilium-operator
      annotations:
        summary: "Cilium Operator 实例下线"
        description: "Cilium Operator 实例 {{ $labels.pod }} 已经下线超过 1 分钟"

    - alert: CiliumOperatorErrorRateHigh
      expr: sum(rate(cilium_operator_errors_warnings_total{level="error"}[5m])) by (pod) > 0.05
      for: 2m
      labels:
        severity: warning
        component: cilium-operator
      annotations:
        summary: "Cilium Operator 错误率过高"
        description: "Cilium Operator 实例 {{ $labels.pod }} 错误率为 {{ $value }} 错误/秒，持续 2 分钟"

    - alert: CiliumLBIPAMServiceUnsatisfied
      expr: sum(cilium_operator_lbipam_services_unsatisfied) > 5
      for: 3m
      labels:
        severity: warning
        component: cilium-operator
      annotations:
        summary: "LB IPAM 未能分配 IP 的服务过多"
        description: "有 {{ $value }} 个服务未能获得 LoadBalancer IP 地址，持续 3 分钟"

  - name: cilium.network.rules
    interval: 30s
    rules:
    # 网络相关告警 - 高优先级丢包原因
    - alert: CiliumDropConnectionTrackingFailure
      expr: sum(rate(hubble_drop_total{reason=~"CT_MAP_INSERTION_FAILED|CT_TRUNCATED_OR_INVALID_HEADER|CT_NO_MAP_FOUND"}[5m])) by (reason, node) > 1
      for: 2m
      labels:
        severity: critical
        component: cilium-network
        drop_category: connection_tracking
      annotations:
        summary: "Cilium 连接跟踪相关丢包严重"
        description: "节点 {{ $labels.node }} 上由于 {{ $labels.reason }} 导致的丢包率为 {{ $value }} 包/秒，连接跟踪可能存在问题"

    - alert: CiliumDropServiceLoadBalancingFailure
      expr: sum(rate(hubble_drop_total{reason=~"SERVICE_BACKEND_NOT_FOUND|DENIED_BY_LB_SRC_RANGE_CHECK"}[5m])) by (reason, node) > 1
      for: 2m
      labels:
        severity: critical
        component: cilium-network
        drop_category: service_lb
      annotations:
        summary: "Cilium 服务负载均衡相关丢包严重"
        description: "节点 {{ $labels.node }} 上由于 {{ $labels.reason }} 导致的丢包率为 {{ $value }} 包/秒，服务配置可能存在问题"

    - alert: CiliumDropNetworkConfigFailure
      expr: sum(rate(hubble_drop_total{reason=~"FIB_LOOKUP_FAILED|NO_EGRESS_GATEWAY"}[5m])) by (reason, node) > 1
      for: 3m
      labels:
        severity: critical
        component: cilium-network
        drop_category: network_config
      annotations:
        summary: "Cilium 网络配置相关丢包严重"
        description: "节点 {{ $labels.node }} 上由于 {{ $labels.reason }} 导致的丢包率为 {{ $value }} 包/秒，网络路由或配置存在问题"

    # 中等优先级丢包原因
    - alert: CiliumDropRateLimitingIssue
      expr: sum(rate(hubble_drop_total{reason=~"DROP_RATE_LIMITED|REACHED_EDT_RATE_LIMITING_DROP_HORIZON"}[5m])) by (reason, node) > 5
      for: 5m
      labels:
        severity: warning
        component: cilium-network
        drop_category: rate_limiting
      annotations:
        summary: "Cilium 速率限制丢包"
        description: "节点 {{ $labels.node }} 上由于 {{ $labels.reason }} 导致的丢包率为 {{ $value }} 包/秒，可能需要调整速率限制配置"

    - alert: CiliumDropDataPathNotReady
      expr: sum(rate(hubble_drop_total{reason=~"DROP_HOST_NOT_READY|DROP_EP_NOT_READY"}[5m])) by (reason, node) > 2
      for: 3m
      labels:
        severity: warning
        component: cilium-network
        drop_category: datapath_readiness
      annotations:
        summary: "Cilium 数据路径未就绪丢包"
        description: "节点 {{ $labels.node }} 上由于 {{ $labels.reason }} 导致的丢包率为 {{ $value }} 包/秒，数据路径可能尚未完全就绪"

    - alert: CiliumPolicyChangeFailureHigh
      expr: sum(rate(cilium_policy_change_total{outcome="failure"}[5m])) by (node) > 0.1
      for: 2m
      labels:
        severity: warning
        component: cilium-policy
      annotations:
        summary: "Cilium 网络策略变更失败率过高"
        description: "节点 {{ $labels.node }} 上的网络策略变更失败率为 {{ $value }} 次/秒，持续 2 分钟"

    - alert: CiliumEndpointDisconnecting
      expr: sum(cilium_endpoint_state{endpoint_state="disconnecting"}) by (node) > 10
      for: 5m
      labels:
        severity: warning
        component: cilium-network
      annotations:
        summary: "Cilium 端点连接异常数量过多"
        description: "节点 {{ $labels.node }} 上有 {{ $value }} 个端点处于断开连接状态，持续 5 分钟"

  - name: cilium.resources.rules
    interval: 30s
    rules:
    # 资源相关告警
    - alert: CiliumBPFMapPressureHigh
      expr: max(cilium_bpf_map_pressure) by (node) > 0.8
      for: 3m
      labels:
        severity: warning
        component: cilium-ebpf
      annotations:
        summary: "Cilium eBPF Map 存储压力过高"
        description: "节点 {{ $labels.node }} 上的 eBPF Map 存储压力为 {{ $value | humanizePercentage }}，超过 80%"

    - alert: CiliumBPFMapPressureCritical
      expr: max(cilium_bpf_map_pressure) by (node) > 0.95
      for: 1m
      labels:
        severity: critical
        component: cilium-ebpf
      annotations:
        summary: "Cilium eBPF Map 存储压力严重"
        description: "节点 {{ $labels.node }} 上的 eBPF Map 存储压力为 {{ $value | humanizePercentage }}，超过 95%，可能影响网络功能"

    - alert: CiliumBPFMapOperationFailureRateHigh
      expr: sum(rate(cilium_bpf_map_ops_total{outcome!="success"}[5m])) by (node) > 1
      for: 3m
      labels:
        severity: warning
        component: cilium-ebpf
      annotations:
        summary: "Cilium eBPF Map 操作失败率过高"
        description: "节点 {{ $labels.node }} 上的 eBPF Map 操作失败率为 {{ $value }} 次/秒，持续 3 分钟"

    - alert: CiliumIPPoolUtilizationCritical
      expr: (sum(cilium_ip_addresses{family="ipv4"}) by (node)) / (sum(cilium_ipam_capacity{family="ipv4"}) by (node)) > 0.9
      for: 2m
      labels:
        severity: critical
        component: cilium-ipam
      annotations:
        summary: "Cilium IP 池使用率严重"
        description: "节点 {{ $labels.node }} 上的 IP 池使用率为 {{ $value | humanizePercentage }}，超过 90%，可能导致 Pod 创建失败"

  - name: cilium.cluster.rules
    interval: 30s
    rules:
    # 集群相关告警
    - alert: CiliumClusterMeshFailureHigh
      expr: sum(cilium_clustermesh_remote_cluster_failures) by (node) > 0
      for: 3m
      labels:
        severity: warning
        component: cilium-clustermesh
      annotations:
        summary: "Cilium 集群网格连接失败"
        description: "节点 {{ $labels.node }} 上有 {{ $value }} 个远程集群连接失败，持续 3 分钟"

    - alert: HubbleLostEventsHigh
      expr: sum(rate(hubble_lost_events_total[5m])) by (node) > 100
      for: 3m
      labels:
        severity: warning
        component: hubble
      annotations:
        summary: "Hubble 丢失事件过多"
        description: "节点 {{ $labels.node }} 上的 Hubble 丢失事件率为 {{ $value }} 事件/秒，持续 3 分钟"

  - name: cilium.availability.rules
    interval: 30s
    rules:
    # 可用性相关告警
    - alert: CiliumAgentRestartFrequent
      expr: increase(kube_pod_container_status_restarts_total{container="cilium-agent"}[1h]) > 3
      for: 0m
      labels:
        severity: warning
        component: cilium-agent
      annotations:
        summary: "Cilium Agent 频繁重启"
        description: "Pod {{ $labels.pod }} 在过去 1 小时内重启了 {{ $value }} 次"

    - alert: CiliumOperatorRestartFrequent
      expr: increase(kube_pod_container_status_restarts_total{container="cilium-operator"}[1h]) > 2
      for: 0m
      labels:
        severity: warning
        component: cilium-operator
      annotations:
        summary: "Cilium Operator 频繁重启"
        description: "Pod {{ $labels.pod }} 在过去 1 小时内重启了 {{ $value }} 次"
